# Generated by Django 4.2.6 on 2023-10-09 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('centralidea', models.CharField(max_length=25)),
                ('lineofeinquiry', models.CharField(max_length=25)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.grades')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('subject_code', models.CharField(max_length=30)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.grades')),
            ],
        ),
    ]
