# Generated by Django 4.2.6 on 2023-10-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_theme_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='lineofeinquiry',
            new_name='lineofinquiry',
        ),
    ]
