# Generated by Django 4.2.6 on 2023-10-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_lineofeinquiry_theme_lineofinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentType', models.CharField(max_length=256)),
                ('assessmentName', models.CharField(max_length=256)),
                ('assessmentFor', models.CharField(max_length=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.grades')),
                ('subject', models.ManyToManyField(blank=True, null=True, to='mainapp.subject')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.theme')),
            ],
        ),
    ]
