# Generated by Django 4.2.6 on 2023-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_markentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markentry',
            name='marks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
