# Generated by Django 4.2.6 on 2023-10-09 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_markentry_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='markentry',
            name='subject_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject'),
        ),
    ]
